version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourname/PROJECT_NAME:latest # Altere
    container_name: PROJECT_NAME_CONTAINER # Altere
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html/PROJECT_NAME # Altere
