version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourname/PROJECT_NAME:latest # Change
    container_name: PROJECT_NAME_CONTAINER # Change
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html/PROJECT_NAME # Change
